/* Frozen ECX catalogue; generated. */
,[ECX_PRIOR_ACTIVE_EXCHANGE_STATE_ROOT_REQUIRED] =
{ .tag = JET
, .jet = simplicity_prior_active_exchange_state_root_required
, .cmr = {{0xe1e932deu, 0xa61f43f2u, 0x9e063737u, 0xca8b5915u, 0x25fe1724u, 0x081fe166u, 0x4087300cu, 0xfdb4ba46u}}
, .sourceIx = ty_u
, .targetIx = ty_w256
, .cost = 1000 /* milli weight units */
}
,[ECX_PRIOR_ACTIVE_FORCED_INBOX_ROOT_REQUIRED] =
{ .tag = JET
, .jet = simplicity_prior_active_forced_inbox_root_required
, .cmr = {{0x25d93db6u, 0xac9bd1a3u, 0xdc0de7d2u, 0x57687151u, 0x668aeadcu, 0xe1b558f4u, 0x6934b0afu, 0x2518b5ceu}}
, .sourceIx = ty_u
, .targetIx = ty_w256
, .cost = 1000 /* milli weight units */
}
,[ECX_PRIOR_ACTIVE_DEPOSIT_INBOX_ROOT_REQUIRED] =
{ .tag = JET
, .jet = simplicity_prior_active_deposit_inbox_root_required
, .cmr = {{0x2f63ecc2u, 0x74d39882u, 0x88d1df57u, 0xf597d7eeu, 0x850f69cau, 0x5b90a998u, 0x1269eeb7u, 0x3cbe4e3cu}}
, .sourceIx = ty_u
, .targetIx = ty_w256
, .cost = 1000 /* milli weight units */
}
,[ECX_PRIOR_ACTIVE_FORCED_PROCESSED_CURSOR_REQUIRED] =
{ .tag = JET
, .jet = simplicity_prior_active_forced_processed_cursor_required
, .cmr = {{0x5e1fe056u, 0x0964b537u, 0x63a56fb9u, 0xb8a904a3u, 0x32277668u, 0x3a15e5a2u, 0x2be0fcf3u, 0x4051adf7u}}
, .sourceIx = ty_u
, .targetIx = ty_w64
, .cost = 1000 /* milli weight units */
}
,[ECX_PRIOR_ACTIVE_DEPOSIT_PROCESSED_CURSOR_REQUIRED] =
{ .tag = JET
, .jet = simplicity_prior_active_deposit_processed_cursor_required
, .cmr = {{0xe4b9f8edu, 0x7375be90u, 0x4ae872fdu, 0x90ccda6au, 0xa2e2afc4u, 0xf804e7ffu, 0x1054acccu, 0x3aa23d49u}}
, .sourceIx = ty_u
, .targetIx = ty_w64
, .cost = 1000 /* milli weight units */
}
,[ECX_CURRENT_BMM_PARENT_BLOCK_HASH_REQUIRED] =
{ .tag = JET
, .jet = simplicity_current_bmm_parent_block_hash_required
, .cmr = {{0xd0818b4cu, 0xfeba941cu, 0x745471adu, 0x145a3c5du, 0xc0103567u, 0x6de669eau, 0xa110b18du, 0x2b9ad587u}}
, .sourceIx = ty_u
, .targetIx = ty_w256
, .cost = 1000 /* milli weight units */
}
,[ECX_CURRENT_BMM_PARENT_HEIGHT_REQUIRED] =
{ .tag = JET
, .jet = simplicity_current_bmm_parent_height_required
, .cmr = {{0x9e981e3fu, 0x54cec2d4u, 0x50489700u, 0xaded945du, 0xfae6f471u, 0x41ad10aeu, 0x5a5c5fb4u, 0x989202d2u}}
, .sourceIx = ty_u
, .targetIx = ty_w64
, .cost = 1000 /* milli weight units */
}
,[ECX_CURRENT_BMM_PARENT_MTP_REQUIRED] =
{ .tag = JET
, .jet = simplicity_current_bmm_parent_mtp_required
, .cmr = {{0x97e6be18u, 0x16d79d74u, 0xa61f2595u, 0x4ac1a656u, 0xabd687c0u, 0xa394f9e7u, 0x98eb9ac2u, 0x62d03c5du}}
, .sourceIx = ty_u
, .targetIx = ty_w64
, .cost = 1000 /* milli weight units */
}
,[ECX_VERIFY_SP1_GROTH16_SHA256] =
{ .tag = JET
, .jet = simplicity_verify_sp1_groth16_sha256
, .cmr = {{0xb1694ea4u, 0x5d838e5du, 0x43912c49u, 0x3a2a6611u, 0xc2c2c59eu, 0x53e6ec05u, 0xf1401451u, 0x7718428du}}
, .sourceIx = ty_ecx_pw256w256
, .targetIx = ty_b
, .cost = 1000 /* milli weight units */
}
